rt-dev:
  user: root
  hostname: ws.rt.gw
  deploy_path: /opt/easyengine/sites/rt-webstories.rt.gw/app

rt-demo:
  user: root
  hostname: ws.rt.gw
  deploy_path: /opt/easyengine/sites/google-webstories.rt.gw/app
